ALTER TABLE "MedicalCenter" ADD COLUMN IF NOT EXISTS "images" JSONB;
ALTER TABLE "MedicalCenter" ADD COLUMN IF NOT EXISTS "videoUrl" TEXT;
ALTER TABLE "MedicalCenter" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "MedicalCenter" ADD COLUMN IF NOT EXISTS "heroImage" TEXT;
ALTER TABLE "MedicalCenter" ADD COLUMN IF NOT EXISTS "brandColor" TEXT;
ALTER TABLE "MedicalCenter" ADD COLUMN IF NOT EXISTS "features" JSONB;
ALTER TABLE "MedicalCenter" ADD COLUMN IF NOT EXISTS "services" JSONB;
